### ISSUE TITLE
[Epic] Create a Dutch City Finder Application

### ISSUE THREAD

**Issue by LahiruRajapaksha** [LahiruRajapaksha/dutch-city-finder-v1#1]
#### Tasks

- [ ] Create a wireframe for the UI
- [ ] Implement the data fetching logic
- [ ] Implement the UI interfaces
- [ ] Styling
- [ ] Internationalization

**Comment by LahiruRajapaksha** [comment]
Updated wireframes

![WireFrame](https://github.com/LahiruRajapaksha/dutch-city-finder-v1/assets/29033481/13efa0db-c826-4cae-9383-3cdf0e74bc0b)

**Comment by LahiruRajapaksha** [comment]
### Update up to today (2023-10-25)


### What did I do
- Created the wireframes and finalized the basic design of the UI. 
- Initially started the project with `create-react-app` and started to configure the project for development. Moving forward with the web pack, it's observed that it takes much time to start the dev server and reflect a change to the DOM. So, I moved to use Vite.
- Incorporated the functionality of the Tanstack query library with Axios for data fetching.
- Build the components using the MUI v5 and style them.
- After finishing the main parts of the components, I thought to try to incorporate the usage of `Intersection Observer API`s functionality into the application.

### Any Blockers Faced?
No. Initially, I had some issues with the `create-react-app` project configuration for the development when it came to configuring the Lint, Prettier (Only to facilitate the coding experience), but after moving to Vite, it also solved. Rather than this, there were no significant blockers found when implementing the application.
